/**
 * This code was generated by Builder.io.
 */
import React from 'react'

type CloneTemplateProps = {
	text: string
}

function CloneTemplate({ text }: CloneTemplateProps) {
	return (
		<button className="flex relative gap-px justify-center items-start self-stretch p-px my-auto text-sm font-medium leading-6 text-center text-white max-w-[200px] rounded-[99px] w-[138px]">
			<div className="flex absolute inset-0 z-0 shrink-0 self-start bg-white bg-opacity-10 h-[46px] rounded-[99px] w-[138px]" />
			<div className="flex z-0 flex-col flex-1 shrink justify-center px-4 py-2.5 pr-4 my-auto border-4 border-solid shadow-sm backdrop-blur-[60px] basis-0 border-zinc-950 rounded-[99px]">
				<span>{text}</span>
			</div>
		</button>
	)
}

export default CloneTemplate
