/**
 * This code was generated by Builder.io.
 */
import React from 'react'

type IconButtonProps = {
	iconSrc: string
	altText: string
}

function IconButton({ iconSrc, altText }: IconButtonProps) {
	return (
		<button className="flex flex-col justify-center items-center self-stretch px-3.5 my-auto rounded-xl border border-solid shadow-sm border-zinc-900 h-[50px] w-[50px]">
			<div className="flex flex-col w-full">
				<div className="flex items-start w-full">
					<img
						loading="lazy"
						src={iconSrc}
						alt={altText}
						className="object-contain w-6 aspect-square"
					/>
				</div>
			</div>
		</button>
	)
}

export default IconButton
