-- Neurelo Generated Migration
-- Description: This migration was automatically generated by Neurelo
/*
Warnings:

- You are about to drop the `profile` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "user"
DROP CONSTRAINT "user_id_fkey";

-- DropIndex
DROP INDEX "user_id_key";

-- DropTable
DROP TABLE "profile";