/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Header from './Header'
import MainContent from './MainContent'
import Footer from './Footer'

function App() {
	return (
		<div className="flex flex-col min-h-screen">
			<Header title="AI Writing Assistant" />
			<MainContent />
			<Footer />
		</div>
	)
}

export default App
