/**
 * This code was generated by Builder.io.
 */
import React from 'react'

function Footer() {
	return (
		<footer className="bg-gray-800 text-white py-4">
			<div className="container mx-auto text-center">
				<p>&copy; 2023 AI Writing Assistant. All rights reserved.</p>
			</div>
		</footer>
	)
}

export default Footer
