/**
 * This code was generated by Builder.io.
 */
import React from 'react'
import Navigation from './Navigation'

type HeaderProps = {
	title: string
}

function Header({ title }: HeaderProps) {
	return (
		<header className="bg-gradient-to-b from-white to-transparent p-4">
			<h1 className="text-3xl font-bold text-center">{title}</h1>
			<Navigation />
		</header>
	)
}

export default Header
