/**
 * This code was generated by Builder.io.
 */
import React from 'react'

const MENU_ITEMS = [
	{ label: 'Home', href: '#' },
	{ label: 'About', href: '#' },
	{ label: 'Services', href: '#' },
	{ label: 'Contact', href: '#' }
]

function Navigation() {
	return (
		<nav className="mt-4">
			<ul className="flex justify-center space-x-4">
				{MENU_ITEMS.map(item => (
					<li key={item.label}>
						<a
							href={item.href}
							className="text-blue-600 hover:text-blue-800"
						>
							{item.label}
						</a>
					</li>
				))}
			</ul>
		</nav>
	)
}

export default Navigation
